[package]
name = "buildx_seroost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.95"
xml-rs = "0.8.4"
tiny_http = "0.11"
anyhow = "1.0.70"
